name: release-container
on:
  push:
    branches:
      - 'main'
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - run: git fetch --prune --unshallow

      - name: log-into-docker-hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
      - name: print tag
        run: echo "$(git describe --tags --abbrev=0)"

      - name: build-container
        run: docker build -t francescomecatti/doorbellcam:$(git describe --tags --abbrev=0) .

      - name: push-image
        run: docker push francescomecatti/doorbellcam:$(git describe --tags --abbrev=0)