name: release-container
on:
  push:
    branches:
      - 'main'
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - run: git fetch --prune --unshallow

      - name: log-into-docker-hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
      - name: print tag
        run: echo "$(git describe --tags --abbrev=0)"

      - name: build-container-push-image
        run: export DOCKER_CLI_EXPERIMENTAL=enabled
        run: docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
        run: docker pull tonistiigi/binfmt:latest
        run: docker run --privileged --rm tonistiigi/binfmt --uninstall qemu-arm
        run: docker run --privileged --rm tonistiigi/binfmt --uninstall qemu-aarch64
        run: docker run --privileged --rm tonistiigi/binfmt --uninstall qemu-ppc64le
        run: docker run --privileged --rm tonistiigi/binfmt --uninstall qemu-s390x
        run: docker run --privileged --rm tonistiigi/binfmt --install all
        run: docker buildx create --use --name multi-arch-builder
        run: docker buildx build --platform linux/arm64 -t francescomecatti/doorbellcam-arm:v2.0 --push .
